option (USE_SYSTEM_CXXOPTS "Set to OFF to use system lz4 library instead of bundled" OFF)

if (USE_SYSTEM_CXXOPTS)
    find_library (CXXOPTS_LIBRARY cxxopts)
    find_path (CXXOPTS_INCLUDE_DIR NAMES cxxopts.hpp )
else(USE_SYSTEM_CXXOPTS)
	if (NOT EXISTS "${CMAKE_SOURCE_DIR}/contrib/cxxopts/include/cxxopts.hpp")
		message( FATAL_ERROR "submodule contrib/cxxopts is missing. to fix try run: \n git submodule update --init --recursive" )
	endif()
    set (CXXOPTS_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/contrib/cxxopts/include)
    set (CXXOPTS_LIBRARY cxxopts)
    set (USE_INTERNAL_CXXOPTS_LIBRARY 1)
endif ()

message (STATUS "Using cxxopts: ${CXXOPTS_INCLUDE_DIR} : ${CXXOPTS_LIBRARY}")
